name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: 'stable'
      
      - name: Install dependencies
        run: nimble install -y
      
      - name: Extract version from tag
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=0.0.0" >> $GITHUB_OUTPUT
          fi
      
      - name: Build Debug binary
        run: nimble build
      
      - name: Build Release binary
        run: nimble build -d:release
      
      - name: Compress binaries
        run: |
          tar -czf "nitch-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz" nitch
          sha256sum "nitch-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz" > "nitch-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz.sha256"
      
      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nitch-${{ steps.get_version.outputs.VERSION }}-debug
          path: nitch
          retention-days: 7
      
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nitch-${{ steps.get_version.outputs.VERSION }}-release
          path: |
            nitch-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz
            nitch-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz.sha256
          retention-days: 30
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nitch-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz
            nitch-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz.sha256
          draft: false
          prerelease: false
